print('¿Que sale de la cruza entre un mono y un pato?')
input()
print('¡Un monopatin!')
print()
print('¿Por que vuelan los pajaros pa\'l sur?')
input()
print('¡Porque caminando tardarian demasiado!')
print()
print('¿En que se parecen una familia, un bombero y un barco?')
input()
print("No sé...¿En que se parecen?")
input()
print('En que el bombero y el barco tienen casco.')
input()
print('¿Y la familia?', end='')
print(' -Good, thank.')
